version: '3.2'

services:
  web:
    build:
      context: .
    ports:
      - '8080:80'
    environment:
      - 'GUNICORN_CMD_ARGS="--proxy-protocol"'
    volumes:
      - type: bind
        source: ./app
        target: /app
